# Generated by Django 5.2 on 2025-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='Visitantes'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='Visitantes'),
        ),
    ]
