# Generated by Django 5.2.1 on 2025-05-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AbraArte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('sala', models.CharField(max_length=100)),
                ('obras', models.ManyToManyField(related_name='exposiciones', to='AbraArte.obraarte')),
            ],
        ),
    ]
