# Generated by Django 5.2.1 on 2025-05-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descipcion', models.CharField(max_length=255)),
                ('ejemplares', models.IntegerField()),
                ('aorigen', models.IntegerField()),
                ('autor', models.CharField(max_length=255)),
            ],
        ),
    ]
