# Generated by Django 5.2.1 on 2025-05-20 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exposicion', '0001_initial'),
        ('Visitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('exposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exposicion.exposicion')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitante.visitante')),
            ],
        ),
    ]
