# Generated by Django 5.2.1 on 2025-05-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(default=''),
        ),
    ]
