# Generated by Django 5.2 on 2025-06-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0003_alter_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='Reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='Reserva'),
        ),
    ]
