# Generated by Django 5.2.1 on 2025-05-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Genero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Genero.genero')),
            ],
        ),
    ]
