# Generated by Django 5.2.1 on 2025-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='presupuesto',
            field=models.CharField(),
        ),
    ]
