# Generated by Django 5.2.1 on 2025-05-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pelicula', '0002_alter_pelicula_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
