# Generated by Django 5.2 on 2025-06-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pelicula', '0003_alter_pelicula_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='Pelicula'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='Pelicula'),
        ),
    ]
