# Generated by Django 5.2 on 2025-05-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('anio', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
    ]
