# Generated by Django 5.2 on 2025-05-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='popularidad',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
