# Generated by Django 5.2 on 2025-05-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=5)),
                ('genero', models.CharField(max_length=10)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tipo.tipo')),
            ],
        ),
    ]
