# Generated by Django 5.2 on 2025-06-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='Artistas'),
        ),
    ]
