# Generated by Django 5.2 on 2025-06-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbraArte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraarte',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='AbraArte'),
        ),
        migrations.AddField(
            model_name='obraarte',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='AbraArte'),
        ),
    ]
